//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.MyDemographicsInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyDemographicsInfoService.IMyDemographicsInfoService")]
    public interface IMyDemographicsInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsWithOutDB", ReplyAction="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsWithOutDBResponse")]
        System.Data.DataSet GetDemographicsWithOutDB();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsWithOutDB", ReplyAction="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsWithOutDBResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsWithOutDBAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithConfig", ReplyAction="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithConfigRes" +
            "ponse")]
        System.Data.DataSet GetDemographicsUsingDBWithConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithConfig", ReplyAction="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithConfigRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithConfigAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithOutConfig" +
            "", ReplyAction="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithOutConfig" +
            "Response")]
        System.Data.DataSet GetDemographicsUsingDBWithOutConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithOutConfig" +
            "", ReplyAction="http://tempuri.org/IMyDemographicsInfoService/GetDemographicsUsingDBWithOutConfig" +
            "Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithOutConfigAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyDemographicsInfoServiceChannel : Business.MyDemographicsInfoService.IMyDemographicsInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyDemographicsInfoServiceClient : System.ServiceModel.ClientBase<Business.MyDemographicsInfoService.IMyDemographicsInfoService>, Business.MyDemographicsInfoService.IMyDemographicsInfoService {
        
        public MyDemographicsInfoServiceClient() {
        }
        
        public MyDemographicsInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyDemographicsInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDemographicsInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyDemographicsInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetDemographicsWithOutDB() {
            return base.Channel.GetDemographicsWithOutDB();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsWithOutDBAsync() {
            return base.Channel.GetDemographicsWithOutDBAsync();
        }
        
        public System.Data.DataSet GetDemographicsUsingDBWithConfig() {
            return base.Channel.GetDemographicsUsingDBWithConfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithConfigAsync() {
            return base.Channel.GetDemographicsUsingDBWithConfigAsync();
        }
        
        public System.Data.DataSet GetDemographicsUsingDBWithOutConfig() {
            return base.Channel.GetDemographicsUsingDBWithOutConfig();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDemographicsUsingDBWithOutConfigAsync() {
            return base.Channel.GetDemographicsUsingDBWithOutConfigAsync();
        }
    }
}
